
facts = {
    "1" : "I was a quick study. I was so young when I wrote my first piece for violin and piano that I needed my father's help—not to write the music, but to hold my pencil! HAHAHAHAHHA .",
    "2": "I had big ambitions. Shortly after I started composing, I got serious: I wrote a major mass and my first opera at age 12.",
    "3": "Haydn and I were friends. Haydn was already a famous and very respected composer when I was still a child, but our age difference didn't prevent us from becoming friends later. Haydn praised me endlessly in letters to friends and in conversation. He wrote to one friend, 'If only I could impress my inimitable works on the soul of every friend of music, and the souls of high personages in particular, as deeply, with the same musical understanding and with the same deep feeling, as I understand and feel them, the nations would vie with each other to possess such a jewel.' I often confided without bitterness that I, not Haydn, was the real genius of the age.",
    "4": "My father was a composer, too. I may not have needed much help with my compositions at an early age, but my father certainly could have helped. Leopold Mozart was a composer before I was even born, and later, he wrote a fair number of pieces inspired by me.",
    "5": "I was small. According to multiple biographers, I was extremely short at about 5'4″. 'I was a remarkably small man, very thin and pale, with a profusion of fine, fair hair of which I was rather vain,' said the tenor Michael Kelly. My complexion was uneven and blotchy, with marks left over from a childhood bout of smallpox. My speaking voice, according to my wife Constanze, was very high, but could be loud and commanding when I wanted it to be.",
    "6": "I loved shopping. I spent lavishly on beautiful clothing as an adult. Tenor Michael Kelly remembered one outfit I wore to rehearsal: '[I] was on the stage with my crimson pelisse and gold-laced cocked hat, giving the time of the music to the orchestra.'",
    "7": "I composed in short bursts throughout the day. I didn't spend my whole day composing; rather, I did a little writing in the morning, a little in the afternoon, and a little at night. I was quite a night owl and didn't seem to need much sleep.",
    "8": "I made friends with all kinds of people. Franz Joseph Haydn was one of my friends, but I also knew countless other musicians, performers, aristocrats, and Salzburg residents who had a variety of jobs. Some of my closest friends were counts, scientists, and doctors.",
    "9": "I had lots of pets. I had unusual taste in house animals. At different points in my life, I kept a canary, a starling, a dog, and a horse.",
    "10": "I had a strange sense of humor. The jokes I told as an adult were similar to the jokes today's young boys would laugh at. Some of Austria's high society found my humor off-putting, especially when combined with my taste for fine clothing, but my true friends either had similar taste or found the jokes charming."
}
